# Generated by Django 6.0.2 on 2026-03-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0002_alter_adoptionapplication_id_alter_adoptionmatch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoptionapplication",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="adoptionmatch",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
