# Generated by Django 5.1.1 on 2026-05-04 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0003_alter_adoptionapplication_id_alter_adoptionmatch_id"),
        ("animals", "0006_alter_animal_animal_agreeableness_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoptionapplication",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="adoptionmatch",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="CloudPetActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("feeding", "喂食"),
                            ("medical", "医疗"),
                            ("playing", "玩耍"),
                            ("grooming", "美容"),
                            ("exercise", "运动"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="活动类型",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", models.TextField(verbose_name="详细内容")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片列表"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_activities",
                        to="animals.animal",
                        verbose_name="动物",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "云养宠物动态",
                "verbose_name_plural": "云养宠物动态列表",
                "db_table": "cloud_pet_activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
