# Generated by Django 6.0.2 on 2026-02-21 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="基地名称")),
                ("description", models.TextField(verbose_name="基地描述")),
                ("address", models.CharField(max_length=200, verbose_name="基地地址")),
                ("contact_name", models.CharField(max_length=50, verbose_name="联系人")),
                ("contact_phone", models.CharField(max_length=11, verbose_name="联系电话")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("website", models.URLField(blank=True, null=True, verbose_name="网站")),
                ("capacity", models.IntegerField(verbose_name="容纳能力")),
                (
                    "current_animals",
                    models.IntegerField(default=0, verbose_name="当前动物数量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("inactive", "不活跃")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "动物基地",
                "verbose_name_plural": "动物基地列表",
                "db_table": "shelters",
            },
        ),
        migrations.CreateModel(
            name="InteractionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("visit", "探访"),
                            ("volunteer", "志愿服务"),
                            ("foster", "寄养"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="申请类型",
                    ),
                ),
                ("purpose", models.TextField(verbose_name="申请目的")),
                ("desired_date", models.DateTimeField(verbose_name="期望日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "review_comments",
                    models.TextField(blank=True, null=True, verbose_name="审核意见"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_applications",
                        to="animals.animal",
                        verbose_name="相关动物",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_interaction_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_applications",
                        to="shelters.shelter",
                        verbose_name="申请基地",
                    ),
                ),
            ],
            options={
                "verbose_name": "互动申请",
                "verbose_name_plural": "互动申请列表",
                "db_table": "interaction_applications",
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="捐赠金额",
                    ),
                ),
                (
                    "goods_description",
                    models.TextField(blank=True, null=True, verbose_name="捐赠物品描述"),
                ),
                (
                    "service_description",
                    models.TextField(blank=True, null=True, verbose_name="捐赠服务描述"),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[("money", "金钱"), ("goods", "物品"), ("service", "服务")],
                        max_length=20,
                        verbose_name="捐赠类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="交易ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="捐赠时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="捐赠人",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="shelters.shelter",
                        verbose_name="接收基地",
                    ),
                ),
            ],
            options={
                "verbose_name": "捐赠记录",
                "verbose_name_plural": "捐赠记录列表",
                "db_table": "donations",
            },
        ),
        migrations.CreateModel(
            name="ShelterStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "管理员"),
                            ("staff", "工作人员"),
                            ("volunteer", "志愿者"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="shelters.shelter",
                        verbose_name="所属基地",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelter_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "基地工作人员",
                "verbose_name_plural": "基地工作人员列表",
                "db_table": "shelter_staff",
                "unique_together": {("shelter", "user")},
            },
        ),
    ]
