# Generated by Django 6.0.2 on 2026-02-21 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="活动标题")),
                ("description", models.TextField(verbose_name="活动描述")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("adoption", "领养活动"),
                            ("volunteer", "志愿者活动"),
                            ("fundraising", "筹款活动"),
                            ("education", "教育活动"),
                            ("other", "其他活动"),
                        ],
                        max_length=20,
                        verbose_name="活动类型",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="活动地点")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("capacity", models.IntegerField(verbose_name="参与人数上限")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "即将开始"),
                            ("ongoing", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="活动状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="shelters.shelter",
                        verbose_name="所属基地",
                    ),
                ),
            ],
            options={
                "verbose_name": "基地活动",
                "verbose_name_plural": "基地活动列表",
                "db_table": "shelter_activities",
            },
        ),
    ]
