# Generated by Django 5.1.1 on 2026-02-28 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0005_alter_donation_id_alter_interactionapplication_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={},
        ),
        migrations.AlterModelTable(
            name="donation",
            table=None,
        ),
        migrations.CreateModel(
            name="DonationUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="使用金额"
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("food", "食物采购"),
                            ("medical", "医疗费用"),
                            ("facility", "设施建设"),
                            ("staff", "人员工资"),
                            ("other", "其他用途"),
                        ],
                        max_length=20,
                        verbose_name="使用类型",
                    ),
                ),
                ("purpose", models.CharField(max_length=200, verbose_name="使用目的")),
                ("description", models.TextField(verbose_name="详细说明")),
                ("attachments", models.JSONField(default=list, verbose_name="相关凭证文件")),
                ("usage_date", models.DateField(verbose_name="使用日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_usages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="shelters.donation",
                        verbose_name="对应捐赠",
                    ),
                ),
            ],
            options={
                "verbose_name": "捐赠记录",
                "verbose_name_plural": "捐赠记录列表",
                "db_table": "donations",
            },
        ),
    ]
