# Generated by Django 6.0.2 on 2026-03-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0008_donation_donor_name_alter_donation_donor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={"verbose_name": "捐赠记录", "verbose_name_plural": "捐赠记录列表"},
        ),
        migrations.AlterModelOptions(
            name="donationusage",
            options={"verbose_name": "捐赠使用记录", "verbose_name_plural": "捐赠使用记录列表"},
        ),
    ]
