# Generated by Django 6.0.2 on 2026-03-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shelters",
            "0009_alter_donation_options_alter_donationusage_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="donation",
            table="shelters_donation",
        ),
        migrations.AlterModelTable(
            name="donationusage",
            table="shelters_donationusage",
        ),
    ]
