# Generated by Django 6.0.2 on 2026-03-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0010_donation_donor_name_alter_donation_table_and_more"),
    ]

    operations = [
        # qr_code field already exists in database
    ]
