# Generated by Django 6.0.2 on 2026-03-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0011_donation_donor_name_shelter_qr_code"),
    ]

    operations = [
        # qr_code field already exists in database
        # donor_name field already exists in database
    ]
