# Generated by Django 6.0.2 on 2026-03-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0012_donation_donor_name_alter_shelter_qr_code"),
    ]

    operations = [
        # donor_name field already exists in database
        # qr_code field already exists in database
    ]
