# Generated by Django 6.0.2 on 2026-03-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0013_donation_donor_name_shelter_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="donor_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="捐赠人姓名"
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="qr_code",
            field=models.FileField(
                blank=True, null=True, upload_to="qr_codes/", verbose_name="收款码"
            ),
        ),
    ]
