# Generated by Django 5.1.1 on 2026-03-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0014_donation_donor_name_shelter_qr_code"),
    ]

    operations = [
        # 先清空 qr_code 数据，避免类型转换冲突
        migrations.RunSQL(
            sql="UPDATE shelters SET qr_code = NULL WHERE qr_code IS NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 然后修改字段类型为 JSONField
        migrations.AlterField(
            model_name="donation",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="donationusage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="interactionapplication",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="qr_code",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="收款码 Base64 数据"
            ),
        ),
        migrations.AlterField(
            model_name="shelteractivity",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shelterstaff",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
