# Generated by Django 6.0.2 on 2026-02-21 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("education", models.CharField(max_length=50, verbose_name="学历")),
                ("occupation", models.CharField(max_length=100, verbose_name="职业")),
                ("skills", models.CharField(max_length=200, verbose_name="技能特长")),
                (
                    "availability",
                    models.CharField(max_length=200, verbose_name="可服务时间"),
                ),
                (
                    "experience",
                    models.TextField(blank=True, null=True, verbose_name="志愿者经历"),
                ),
                (
                    "motivation",
                    models.TextField(blank=True, null=True, verbose_name="志愿服务动机"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "志愿者资料",
                "verbose_name_plural": "志愿者资料列表",
                "db_table": "volunteer_profiles",
            },
        ),
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "已报名"),
                            ("attended", "已参加"),
                            ("absent", "未参加"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="参与状态",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="报名时间"),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与者",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动参与者",
                "verbose_name_plural": "活动参与者列表",
                "db_table": "activity_participants",
            },
        ),
        migrations.CreateModel(
            name="VolunteerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="活动名称")),
                ("description", models.TextField(verbose_name="活动描述")),
                ("location", models.CharField(max_length=200, verbose_name="活动地点")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("capacity", models.IntegerField(verbose_name="参与人数上限")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "策划中"),
                            ("upcoming", "即将开始"),
                            ("ongoing", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="活动状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="组织者",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="participated_activities",
                        through="volunteers.ActivityParticipant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与者",
                    ),
                ),
            ],
            options={
                "verbose_name": "志愿者活动",
                "verbose_name_plural": "志愿者活动列表",
                "db_table": "volunteer_activities",
            },
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="volunteers.volunteeractivity",
                verbose_name="活动",
            ),
        ),
        migrations.CreateModel(
            name="VolunteerTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="任务标题")),
                ("description", models.TextField(verbose_name="任务描述")),
                ("location", models.CharField(max_length=200, verbose_name="任务地点")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "required_skills",
                    models.CharField(max_length=200, verbose_name="所需技能"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待分配"),
                            ("assigned", "已分配"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配给",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "志愿者任务",
                "verbose_name_plural": "志愿者任务列表",
                "db_table": "volunteer_tasks",
            },
        ),
        migrations.AlterUniqueTogether(
            name="activityparticipant",
            unique_together={("activity", "participant")},
        ),
    ]
