# Generated by Django 6.0.2 on 2026-03-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0002_alter_activityparticipant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityparticipant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="volunteeractivity",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="volunteertask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
