# Generated by Django 6.0.2 on 2026-03-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0007_alter_donation_id_alter_donationusage_id_and_more"),
        ("volunteers", "0003_alter_activityparticipant_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteeractivity",
            name="shelter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shelter_activities",
                to="shelters.shelter",
                verbose_name="所属基地",
            ),
        ),
    ]
