# Generated by Django 6.0.2 on 2026-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="动物名称")),
                (
                    "species",
                    models.CharField(
                        choices=[("cat", "猫"), ("dog", "狗"), ("other", "其他")],
                        default="cat",
                        max_length=20,
                        verbose_name="物种",
                    ),
                ),
                ("breed", models.CharField(max_length=50, verbose_name="品种")),
                ("age", models.IntegerField(verbose_name="年龄(月)")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "公"), ("female", "母"), ("unknown", "未知")],
                        default="unknown",
                        max_length=20,
                        verbose_name="性别",
                    ),
                ),
                ("weight", models.FloatField(verbose_name="体重(kg)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可领养"),
                            ("adopted", "已领养"),
                            ("pending", "审核中"),
                            ("medical", "医疗中"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("description", models.TextField(verbose_name="描述")),
                ("personality", models.TextField(verbose_name="性格特点")),
                ("health_status", models.TextField(verbose_name="健康状况")),
                ("images", models.JSONField(default=list, verbose_name="图片URL列表")),
                ("found_place", models.CharField(max_length=200, verbose_name="发现地点")),
                ("found_date", models.DateField(verbose_name="发现日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "流浪动物",
                "verbose_name_plural": "流浪动物列表",
                "db_table": "animals",
            },
        ),
    ]
