# Generated by Django 6.0.2 on 2026-02-21 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="shelter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="shelters.shelter",
                verbose_name="所属基地",
            ),
        ),
    ]
