# Generated by Django 5.1.1 on 2026-02-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_animal_shelter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
