# Generated by Django 5.1.1 on 2026-02-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_alter_animal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="animal_agreeableness",
            field=models.FloatField(default=3.0, help_text="动物宜人性"),
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_conscientiousness",
            field=models.FloatField(default=3.0, help_text="动物尽责性"),
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_extraversion",
            field=models.FloatField(default=3.0, help_text="动物外向性"),
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_neuroticism",
            field=models.FloatField(default=3.0, help_text="动物神经质"),
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_openness",
            field=models.FloatField(default=3.0, help_text="动物开放性"),
        ),
    ]
