# Generated by Django 5.1.1 on 2026-05-04 09:31

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0005_alter_animal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="animal_agreeableness",
            field=models.FloatField(
                default=animals.models.generate_default_trait, help_text="动物宜人性"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_conscientiousness",
            field=models.FloatField(
                default=animals.models.generate_default_trait, help_text="动物尽责性"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_extraversion",
            field=models.FloatField(
                default=animals.models.generate_default_trait, help_text="动物外向性"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_neuroticism",
            field=models.FloatField(
                default=animals.models.generate_default_trait, help_text="动物神经质"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_openness",
            field=models.FloatField(
                default=animals.models.generate_default_trait, help_text="动物开放性"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
