# Generated by Django 6.0.2 on 2026-02-21 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_alter_donation_id_alter_interactionapplication_id_and_more"),
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shelter",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager",
                to="shelters.shelter",
                verbose_name="管理的基地",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("normal", "普通用户"),
                    ("volunteer", "志愿者"),
                    ("shelter", "动物基地"),
                    ("admin", "管理员"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
