# Generated by Django 5.1.1 on 2026-02-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_shelter_alter_user_id_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agreeableness",
            field=models.FloatField(default=3.0, help_text="宜人性"),
        ),
        migrations.AddField(
            model_name="user",
            name="conscientiousness",
            field=models.FloatField(default=3.0, help_text="尽责性"),
        ),
        migrations.AddField(
            model_name="user",
            name="extraversion",
            field=models.FloatField(default=3.0, help_text="外向性"),
        ),
        migrations.AddField(
            model_name="user",
            name="neuroticism",
            field=models.FloatField(default=3.0, help_text="神经质"),
        ),
        migrations.AddField(
            model_name="user",
            name="openness",
            field=models.FloatField(default=3.0, help_text="开放性"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
