# Generated by Django 5.1.1 on 2026-02-28 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_comment_id_alter_notification_id_alter_post_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="community.comment",
                verbose_name="父评论",
            ),
        ),
        migrations.CreateModel(
            name="ContentModeration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("post", "帖子"), ("comment", "评论")],
                        max_length=20,
                        verbose_name="内容类型",
                    ),
                ),
                ("content_id", models.IntegerField(verbose_name="内容ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "批准"),
                            ("reject", "拒绝"),
                            ("delete", "删除"),
                            ("warn", "警告"),
                            ("ban", "封禁"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("reason", models.TextField(verbose_name="操作原因")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核员",
                    ),
                ),
            ],
            options={
                "verbose_name": "内容审核记录",
                "verbose_name_plural": "内容审核记录列表",
                "db_table": "content_moderation",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("post", "帖子"), ("comment", "评论"), ("user", "用户")],
                        max_length=20,
                        verbose_name="举报类型",
                    ),
                ),
                ("target_id", models.IntegerField(verbose_name="目标对象ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "垃圾信息"),
                            ("harassment", "骚扰"),
                            ("inappropriate", "不当内容"),
                            ("copyright", "版权侵犯"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="举报原因",
                    ),
                ),
                ("description", models.TextField(verbose_name="详细描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("reviewing", "审核中"),
                            ("resolved", "已解决"),
                            ("dismissed", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, null=True, verbose_name="处理说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="举报时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解决时间"),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_handled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="举报人",
                    ),
                ),
            ],
            options={
                "verbose_name": "举报记录",
                "verbose_name_plural": "举报记录列表",
                "db_table": "community_reports",
            },
        ),
    ]
